# Generated by Django 5.2.5 on 2025-08-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], default='F', help_text='Préférence de genre pour les textes', verbose_name='Je préfère lire les textes au'),
        ),
    ]
