# Generated by Django 5.2.5 on 2025-08-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], help_text='Préférence de genre pour les textes', verbose_name='Je préfère lire les textes au'),
        ),
    ]
