# Generated by Django 5.2.5 on 2025-08-19 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feminine_name', models.CharField(max_length=100)),
                ('masculine_name', models.CharField(max_length=100)),
                ('feeling_family', models.CharField(choices=[('AF', 'Affection'), ('SE', 'Sérénité'), ('JO', 'Joie'), ('IN', 'Intérêt'), ('EN', 'Energie'), ('PE', 'Peur'), ('CO', 'Colère'), ('TR', 'Tristesse'), ('CF', 'Confusion'), ('FA', 'Fatigue'), ('SI', 'Sidération'), ('TE', 'Tension')], help_text="Famille d'émotions", max_length=4, verbose_name="Famille d'émotions")),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('need_family', models.CharField(choices=[('SU', 'Survie'), ('IN', 'Intégrité'), ('RE', 'Réalisation'), ('HA', 'Harmonie'), ('RL', 'Relation'), ('CO', 'Coopération'), ('CE', 'Célébration')], help_text='Famille de besoins', max_length=4, verbose_name='Famille de besoins')),
            ],
        ),
        migrations.CreateModel(
            name='Pause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('empty_your_bag', models.TextField(blank=True, default='', verbose_name='Vide ton sac')),
                ('observation', models.TextField(verbose_name='Observation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
