# Generated by Django 5.2.5 on 2025-08-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pause',
            name='feelings',
            field=models.ManyToManyField(blank=True, related_name='pauses', to='pauses.feeling'),
        ),
        migrations.AddField(
            model_name='pause',
            name='needs',
            field=models.ManyToManyField(blank=True, related_name='pauses', to='pauses.need'),
        ),
    ]
