# Generated by Django 5.2.5 on 2025-08-25 13:02

import pauses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauses', '0002_pause_feelings_pause_needs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pause',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pause empathique', 'verbose_name_plural': 'Pauses empathiques'},
        ),
        migrations.AddField(
            model_name='pause',
            name='title',
            field=models.CharField(default=pauses.models.default_pause_title, max_length=200, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='feminine_name',
            field=models.CharField(max_length=100, verbose_name='Au féminin'),
        ),
        migrations.AlterField(
            model_name='feeling',
            name='masculine_name',
            field=models.CharField(max_length=100, verbose_name='Au masculin'),
        ),
    ]
